config/routes.rb
Rails.application.routes.draw do
  resources :topics
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'topics#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base

  private

    def topic_params
      params.require(:topic).permit(:title, :user_id, :picture, :description, :publish, :date_publish)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ilmu.My</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.1.0/octicons.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/assets/animate.css" rel="stylesheet">
  	<link rel="stylesheet" href="/assets/font-awesome.css" rel="stylesheet">
  	<link rel="stylesheet" href="/assets/nexus.css" rel="stylesheet">
  	<link rel="stylesheet" href="/assets/responsive.css" rel="stylesheet">
  	<link rel="stylesheet" href="/assets/custom.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<div id="pre_header" class="visible-lg" style="background-color:#E4AB7E; height:5px;"></div>
    <div id="header" class="container" style="background-color:#fff; background-image:none;">
        <div class="row">
            <!-- Logo -->
            <div class="logo">
              <%= link_to (image_tag 'logo.jpg',:style=>'padding:20px 50px;'), root_path %>
            </div>
            <!-- End Logo -->
            <!-- Top Menu -->
            <div class="col-md-12 margin-top-30">
                <div id="hornav" class="pull-right visible-lg">
                    <ul class="nav navbar-nav">
                        <li><a href="index.html">Laman Utama</a></li>
                        <li><a href="index.html">Senarai Ilmu</a></li>
                        <li><a href="index.html">Hubungi Kami</a></li>
                        <li><a href="index.html">Info Lanjut</a></li>
                        <li><a href="index.html">Log Masuk</a></li>
                    </ul>
                  </div>
                </div>
                <div class="clear"></div>
                <!-- End Top Menu -->
              </div>
</div>

<div id="pre_header" class="visible-lg" style="background-color:#E4AB7E; height:5px;"></div>
<!-- === END HEADER === -->
<!-- === BEGIN CONTENT === -->
<div id="content" class="container">
  <div class="row margin-vert-30">
    <div class="col-md-9">
      <%= yield %>
    </div>
<!-- === BEGIN SIDEBAR === -->
    <div class="col-md-3">
      <div class="panel panel-primary invert">
        <div class="panel-heading" style="padding:5px 20px;">
        <p class="panel-title">
          <div class="row">
          <%= form_tag( root_path, :method => 'GET' ) do%>
          <div class="input-append" style="padding:4px 8px">
                <%=text_field_tag "q", '', :placeholder => "Cari", :value => params[:q] ,class:"span1 search-query"%>
                <%= button_tag do %>
                <i class="fa fa-search"></i>
                <% end %>
          </div>
          <%end%>
          </div>
        </p>
        </div>
        <div class="panel-body">
        <h5>Kategori</h5>
        <hr>
          <ul>
            <li>Lorem ipsum dolor sit amet,</li>
            <li> consectetur adipisicing e,</li>
            <li>sed do eiusmod tempor incig</li>
            <li>didunt utolore magna aliqua</li>
        <hr>
        </div>
      </div>
    </div>
<!-- === END SIDEBAR === -->
  </div>
</div>
<!-- === END CONTENT === -->
<div id="pre_header" class="visible-lg" style="background-color:#E4AB7E; height:5px;"></div>
<!-- === BEGIN FOOTER === -->
<div id="base">
    <div class="container padding-vert-30">
        <div class="row">
                <!-- Contact Details -->
                <div class="col-md-9 margin-bottom-20">
                    <h3 class="margin-bottom-10">Hubungi Kami</h3>
                    <div class="row">
                      <div class="col-sm-6">
                        <strong>Serai Solutions</strong>
                        <p>41-1-1A Jln Medan PB2B,<br />
                        Pusat Bandar Bangi, Seksyen 9,<br />
                        Bangi 43650, , Selangor, <br />
                        Malaysia.</p>
                        <p>Tel: +603-8926 8989 <br />
                        Fax: +603-8926 8989  <br />
                        Website: <a href="http://www.serai.org/">www.website.com</a></p>
                      </div>
                      <div class="col-sm-6">
                        <p>Nazrol Hafiz <br />
                        Penyelaras Latihan,<br />
                        Serai Solutions. <br />
                        <p>Email: <a href="mailto:info@website.com">admin@serai.org</a><br />
                        Mobile: 013-358 3553 <br />
                      </div>
                    </div>
                <!-- End Contact Details -->
                <!-- Disclaimer -->
                <!-- End Disclaimer -->
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- Footer Menu -->
<div id="footer">
    <div class="container">
        <div class="row">
            <div id="footermenu" class="col-md-8">
                © 2016 Ilmu.My | Designed and developed by Serai Solutions
            </div>
        </div>
    </div>
</div>
<!-- End Footer Menu -->
    <!-- JS -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="/assets/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/scripts.js"></script>
    <!-- Isotope - Portfolio Sorting -->
    <script type="text/javascript" src="/assets/jquery.isotope.js" type="text/javascript"></script>
    <!-- Mobile Menu - Slicknav -->
    <script type="text/javascript" src="/assets/jquery.slicknav.js" type="text/javascript"></script>
    <!-- Animate on Scroll-->
    <script type="text/javascript" src="/assets/jquery.visible.js" charset="utf-8"></script>
    <!-- Slimbox2-->
    <script type="text/javascript" src="/assets/slimbox2.js" charset="utf-8"></script>
    <!-- Modernizr -->
    <script src="/assets/modernizr.custom.js" type="text/javascript"></script>
    <!-- End JS -->
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :publish %><br>
    <%= f.check_box :publish %>
  </div>
  <div class="field">
    <%= f.label :date_publish %><br>
    <%= f.text_field :date_publish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<!-- Tab v2 -->
<h1 class="title">Kongsian Terhangat</h1>
<div class="tabs alternative">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#sample-2a" data-toggle="tab">Sample Heading 1</a></li>
        <li><a href="#sample-2b" data-toggle="tab">Sample Heading 2</a></li>
        <li><a href="#sample-2c" data-toggle="tab">Sample Heading 3</a></li>
        <li><a href="#sample-2d" data-toggle="tab">Sample Heading 4</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="sample-2a">
            <div class="row">
                <div class="col-md-5"><img src="assets/img/frontpage/filler1.jpg" alt="filler image"></div>
                <div class="col-md-7">
                    <h3 class="no-margin no-padding">Humanitatis Per Seacula</h3>
                    <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothicas.</p>
                </div>
            </div>
        </div>
        <div class="tab-pane fade in" id="sample-2b">
            <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
        </div>
        <div class="tab-pane fade in" id="sample-2c">
            <div class="row">
                <div class="col-md-5"><img src="assets/img/frontpage/filler3.jpg" alt="filler image"></div>
                <div class="col-md-7">
                    <h3 class="no-margin no-padding">Mirum Est Notare</h3>
                    <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothicas.</p>
                </div>
            </div>
        </div>
        <div class="tab-pane fade in" id="sample-2d">
            <p>Vivamus imperdiet condimentum diam, eget placerat felis consectetur id. Donec eget orci metus, Vivamus imperdiet condimentum diam, eget placerat felis consectetur id. Donec eget orci metus, ac adipiscing nunc. Pellentesque fermentum, ante ac interdum ullamcorper. Donec eget orci metus, ac adipiscing nunc. Pellentesque fermentum, consectetur id.</p>
            <ul>
                <li>Donec eget orci metus</li>
                <li>Ante ac interdum ullamcorper</li>
                <li>Vivamus imperdiet condimentum</li>
                <li>Pellentesque fermentum</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Tab v2 -->
<div class="margin-bottom-40"><hr></div>
<!-- Tab v3 -->
<h1 class="title">Kongsian Terkini</h1>
<div class="row tabs">
    <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="#sample-3a" data-toggle="tab"><i class="fa fa-home"></i> Sample Heading 1</a></li>
            <li><a href="#sample-3b" data-toggle="tab"><i class="fa fa-cloud"></i> Sample Heading 2</a></li>
            <li><a href="#sample-3c" data-toggle="tab"><i class="fa fa-comments"></i> Sample Heading 3</a></li>
            <li><a href="#sample-3d" data-toggle="tab"><i class="fa fa-gear"></i> Sample Heading 4</a></li>
        </ul>
    </div>
    <div class="col-sm-9">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="sample-3a">
                <div class="row">
                    <div class="col-md-5"><img src="assets/img/frontpage/filler1.jpg" alt="filler image"></div>
                    <div class="col-md-7">
                        <h3 class="no-margin no-padding">Humanitatis Per Seacula</h3>
                        <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothicas.</p>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade in" id="sample-3b">
                <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
            </div>
            <div class="tab-pane fade in" id="sample-3c">
                <div class="row">
                    <div class="col-md-5"><img src="assets/img/frontpage/filler3.jpg" alt="filler image"></div>
                    <div class="col-md-7">
                        <h3 class="no-margin no-padding">Mirum Est Notare</h3>
                        <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothicas.</p>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade in" id="sample-3d">
                <p>Vivamus imperdiet condimentum diam, eget placerat felis consectetur id. Donec eget orci metus, Vivamus imperdiet condimentum diam, eget placerat felis consectetur id. Donec eget orci metus, ac adipiscing nunc. Pellentesque fermentum, ante ac interdum ullamcorper. Donec eget orci metus, ac adipiscing nunc. Pellentesque fermentum, consectetur id.</p>
                <ul>
                    <li>Donec eget orci metus</li>
                    <li>Ante ac interdum ullamcorper</li>
                    <li>Vivamus imperdiet condimentum</li>
                    <li>Pellentesque fermentum</li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @topic.user_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @topic.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @topic.publish %>
</p>

<p>
  <strong>Date publish:</strong>
  <%= @topic.date_publish %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>